services:
  postgres:
    image: postgres:16.14
    container_name: nest_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: landtaxDisputeDb
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: nest_redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: nest_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '5050:80'
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./servers.json:/pgadmin4/servers.json
    depends_on:
      - postgres
volumes:
  postgres_data:
  redis_data:
  pgadmin_data: